name: add env

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        env:
          VITE_APP_TOKEN: ${{ secrets.VITE_APP_TOKEN }}
      - name: gh-pages for Github Action
      - uses: axetroy/gh-pages-action@0.0.21

