name: add env

# Controls when the workflow will run
on:
  page_build:
    branches: [ "gh-pages" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
        env: 
          VITE_APP_TOKEN: ${{ secrets.VITE_APP_TOKEN}}
